### PR TITLE
docs: add transitiongrid theme

### PR DESCRIPTION
**Pull request by brucala**
I forgot to include this in the docs in the previous PR where the transition-grid was inntroduced

### CODE REVIEW

**Comment by frankier** [comment]
Okay! Whoops I didn't notice. Thanks for trying to fix it up. Now it looks like the docs build is broken? Is it from this commit or something else?

**Comment by brucala** [comment]
> Okay! Whoops I didn't notice. Thanks for trying to fix it up. Now it looks like the docs build is broken? Is it from this commit or something else?

Most likely from this commit. Will try to fix it when i find some free time.

**Comment by brucala** [comment]
> Okay! Whoops I didn't notice. Thanks for trying to fix it up. Now it looks like the docs build is broken? Is it from this commit or something else?

@frankier I think now it's really fixed

**Comment by brucala** [comment]
Oh the nightly tests failed :disappointed:. I might be wrong, but by looking at the details I think it's a dependency issue that has nothing to do with this PR.

**Pull request merged**
